n=input('Digite aqui:')
print("Voce digitou {}".format(n))
print('###')
print(type(n))
print(n.isalnum())
print(n.isalpha())
print(n.isdecimal())
print(n.islower())
print(n.isupper())
print(n.isprintable())
print(n.isalnum())
print(n.istitle())