n1= int(input('Digite um número: '))
n2=int(input('Digite mais um número: '))

print("A soma entre {} e {} é={} ".format(n1,n2,n1+n2))
print("############")
print("A subtração entre {} e {} é={} ".format(n1,n2,n1-n2))
print("############")
print("A multiplicação entre {} e {} é={} ".format(n1,n2,n1*n2))
print("############")
print("A divisão entre {} e {} é={:.3f} ".format(n1,n2,n1/n2))
print("############")
print("A potencia de {} elevado {} é={} ".format(n1,n2,n1**n2))
print("############")
print("A potencia com POW de {} elevado {} é={} ".format(n2,n1,pow(n2,n1)))
print("############")
print("A divisão inteira de {} e {} é={} ".format(n1,n2,n1//n2))
print("############")
print("#"*10)
nome= str(input('Digite seu nome: '))
print("Prazer em te conhecer {}!".format(nome))
print("#"*10)
print("[ESCREVE COM 20 ESPACO]Prazer em te conhecer {:20}!".format(nome))
print("#"*10)
print("[ALINHADO A DIREITA 20 ESPACO]Prazer em te conhecer {:>20}!".format(nome))
print("#"*10)
print("[ALINHADO A ESQUERDA 20 ESPACO]Prazer em te conhecer {:<20}!".format(nome))
print("#"*10)
print("[CENTRALIZADO]Prazer em te conhecer {:^20}!".format(nome))
print("#"*10)
print("[CENTRALIZADO COM UM SIMBOLO]Prazer em te conhecer {:=^20}!".format(nome))
print("Não vou deixar quebrar a linha.", end=' ')
print("o barra n deixa quebrar. OLha aqui prazer {}\n seu lindo do \n universo.".format(nome), end=' ')
